export const CITIES_BULGARIA = {
  "Aytos": "Айтос",
  "Asenovgrad": "Асеновград",
  "Berkovitsa": "Берковица",
  "Belene": "Белене",
  "Blagoevgrad": "Благоевград",
  "Botevgrad": "Ботевград",
  "Bregovo": "Брегово",
  "Breznik": "Брезник",
  "Burgas": "Бургас",
  "Byala Slatina": "Бяла Слатина",
  "Cherven Bryag": "Червен бряг",
  "Chirpan": "Чирпан",
  "Dimitrovgrad": "Димитровград",
  "Dobrich": "Добрич",
  "Dryanovo": "Дряново",
  "Dupnitsa": "Дупница",
  "Dve Mogili": "Две могили",
  "Elena": "Елена",
  "Etropole": "Етрополе",
  "Gabrovo": "Габрово",
  "General Toshevo": "Генерал Тошево",
  "Godech": "Годеч",
  "Gorna Oryahovitsa": "Горна Оряховица",
  "Gotse Delchev": "Гоце Делчев",
  "Harmanli": "Харманли",
  "Haskovo": "Хасково",
  "Ihtiman": "Ихтиман",
  "Iskar": "Искър",
  "Isperih": "Исперих",
  "Kalofer": "Калофер",
  "Kardzhali": "Кърджали",
  "Karlovo": "Карлово",
  "Kavarna": "Каварна",
  "Kazanlak": "Казанлък",
  "Knezha": "Кнежа",
  "Kocherinovo": "Кочериново",
  "Kozloduy": "Козлодуй",
  "Kubrat": "Кубрат",
  "Kyustendil": "Кюстендил",
  "Lom": "Лом",
  "Lovech": "Ловеч",
  "Lukovit": "Луковит",
  "Lyaskovets": "Лясковец",
  "Mezdra": "Мездра",
  "Momchilgrad": "Момчилград",
  "Montana": "Монтана",
  "Nesebar": "Несебър",
  "Nikola Kozlevo": "Никола Козлево",
  "Nova Zagora": "Нова Загора",
  "Novi Iskar": "Нови Искър",
  "Oryahovo": "Оряхово",
  "Panagyurishte": "Панагюрище",
  "Parvomay": "Първомай",
  "Pavel Banya": "Павел Баня",
  "Pernik": "Перник",
  "Peshtera": "Пещера",
  "Petrich": "Петрич",
  "Pleven": "Плевен",
  "Plovdiv": "Пловдив",
  "Popovo": "Попово",
  "Pravets": "Правец",
  "Radilovo": "Радилово",
  "Radnevo": "Раднево",
  "Rakovski": "Раковски",
  "Razgrad": "Разград",
  "Rila": "Рила",
  "Roman": "Роман",
  "Rousse": "Русе",
  "Rudozem": "Рудозем",
  "Ruse": "Русе",
  "Samokov": "Самоков",
  "Sandanski": "Сандански",
  "Septemvri": "Септември",
  "Sevlievo": "Севлиево",
  "Shumen": "Шумен",
  "Silistra": "Силистра",
  "Sliven": "Сливен",
  "Smolyan": "Смолян",
  "Sofia": "София",
  "Sozopol": "Созопол",
  "Sungurlare": "Сунгурларе",
  "Suvorovo": "Суворово",
  "Svishtov": "Свищов",
  "Svilengrad": "Свиленград",
  "Targovishte": "Търговище",
  "Tervel": "Тервел",
  "Teteven": "Тетевен",
  "Topolovgrad": "Тополовград",
  "Troyan": "Троян",
  "Troyanovo": "Трояново",
  "Tryavna": "Трявна",
  "Tsarevo": "Царево",
  "Varna": "Варна",
  "Varshets": "Варшетс",
  "Veliki Preslav": "Велики Преслав",
  "Veliko Tarnovo": "Велико Търново",
  "Velingrad": "Велинград",
  "Vidin": "Видин",
  "Vratsa": "Враца",
  "Yablanitsa": "Ябланица",
  "Yakoruda": "Якоруда",
  "Yambol": "Ямбол",
  "Zavet": "Завет",
  "Zlataritsa": "Златарица"
};
